@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul 2>&1
title ChaoXingAgent - Local Dev

set "BACKEND_HOST=127.0.0.1"
set "BACKEND_PORT=8001"
set "FRONTEND_HOST=127.0.0.1"
set "FRONTEND_PORT=3000"
set "NO_COLOR=1"
set "FORCE_COLOR=0"
set "PYTHONUTF8=1"
set "PYTHONIOENCODING=utf-8"
set "DEBUG=true"

cd /d "%~dp0"
set "PROJECT_DIR=%CD%"

echo.
echo ============================================================
echo  ChaoXingAgent - local development launcher
echo ============================================================
echo.
echo [i] Project dir: %PROJECT_DIR%

echo.
echo [1/6] Checking uv...
where uv >nul 2>&1
if errorlevel 1 (
    echo [x] uv was not found.
    echo     Install it with:
    echo     powershell -Command "irm https://astral.sh/uv/install.ps1 ^| iex"
    echo.
    pause
    exit /b 1
)
for /f "delims=" %%v in ('uv --version 2^>nul') do echo     %%v
echo [v] uv is ready.

echo.
echo [2/6] Checking Node.js...
where node >nul 2>&1
if errorlevel 1 (
    echo [!] Node.js was not found. Frontend build and dev server will be skipped.
    echo     Install Node.js 20+ if you need the frontend: https://nodejs.org/
    set "SKIP_FRONTEND=1"
    goto :AFTER_NODE_CHECK
)
for /f "delims=" %%n in ('node --version 2^>nul') do echo     Node.js %%n

where npm >nul 2>&1
if errorlevel 1 (
    echo [!] npm was not found. Frontend build and dev server will be skipped.
    set "SKIP_FRONTEND=1"
    goto :AFTER_NODE_CHECK
)
for /f "delims=" %%p in ('npm --version 2^>nul') do echo     npm     %%p
echo [v] Node.js is ready.
:AFTER_NODE_CHECK

if not exist "%PROJECT_DIR%\frontend\package.json" (
    echo [!] frontend\package.json was not found. Frontend will be skipped.
    set "SKIP_FRONTEND=1"
)

echo.
echo [3/6] Checking .env...
if exist "%PROJECT_DIR%\.env" (
    echo [v] .env already exists.
) else (
    echo [i] Creating default .env for local development...
    (
        echo # ChaoXingAgent local development config
        echo # Generated by start.bat. Edit values as needed.
        echo.
        echo DEBUG=true
        echo STATIC_KEY=chaoxing_dev_static_key
        echo SIGNATURE_TIMEOUT_SECONDS=300
        echo.
        echo # DATABASE_URL=mysql+pymysql://chaoxing:password@127.0.0.1:3306/chaoxing?charset=utf8mb4
        echo.
        echo LLM_PROVIDER=deepseek
        echo LLM_API_KEY=your-api-key-here
        echo LLM_BASE_URL=https://api.deepseek.com
        echo LLM_MODEL=deepseek-chat
        echo LLM_TIMEOUT_SECONDS=60
        echo LLM_TEMPERATURE=0.3
        echo LLM_MAX_TOKENS=4096
        echo.
        echo STUDENT_AGENT_BACKEND=claude
    ) > "%PROJECT_DIR%\.env"
    echo [v] .env created.
    echo [!] Please edit .env and set a real LLM_API_KEY.
)

if not defined SKIP_FRONTEND (
    if exist "%PROJECT_DIR%\frontend\.env.local" (
        echo [v] frontend\.env.local already exists.
    ) else (
        echo [i] Creating frontend\.env.local for local development...
        (
            echo VITE_API_BASE_URL=http://%BACKEND_HOST%:%BACKEND_PORT%/api/v1
            echo VITE_STATIC_KEY=chaoxing_dev_static_key
            echo VITE_DEFAULT_SCHOOL_ID=sch10001
        ) > "%PROJECT_DIR%\frontend\.env.local"
        echo [v] frontend\.env.local created.
    )
)

echo.
echo [4/6] Installing Python dependencies...
if exist "%PROJECT_DIR%\.venv" (
    echo [i] .venv exists. uv will check that dependencies are current.
)
uv sync
if errorlevel 1 (
    echo.
    echo [x] uv sync failed. Check network access and pyproject.toml.
    echo.
    pause
    exit /b 1
)
echo [v] Python dependencies are ready.

echo.
echo [4a/6] Checking optional Claude Agent SDK...
uv run python -c "import claude_agent_sdk" >nul 2>&1
if errorlevel 1 (
    echo [i] claude_agent_sdk is missing. Installing optional Claude dependencies...
    uv sync --extra claude
    if errorlevel 1 (
        echo.
        echo [x] uv sync --extra claude failed. Courseware planning needs claude-agent-sdk.
        echo.
        pause
        exit /b 1
    )
    echo [v] Claude Agent SDK installed.
) else (
    echo [v] Claude Agent SDK is already installed.
)

echo.
if defined SKIP_FRONTEND (
    echo [5/6] Skipping frontend build.
    goto :AFTER_FRONTEND_BUILD
)

echo [5/6] Building frontend...
cd /d "%PROJECT_DIR%\frontend"

if not exist "%PROJECT_DIR%\frontend\node_modules" (
    echo [i] Installing frontend dependencies...
    call npm install
    if errorlevel 1 (
        echo [!] npm install failed. Frontend will be skipped.
        set "SKIP_FRONTEND=1"
        cd /d "%PROJECT_DIR%"
        goto :AFTER_FRONTEND_BUILD
    )
)

echo [i] Running frontend build...
call npm run build
if errorlevel 1 (
    echo [!] npm run build failed. Frontend dev server will be skipped.
    set "SKIP_FRONTEND=1"
    cd /d "%PROJECT_DIR%"
    goto :AFTER_FRONTEND_BUILD
)

cd /d "%PROJECT_DIR%"
echo [v] Frontend build completed.
:AFTER_FRONTEND_BUILD

echo.
echo [i] Releasing old processes on configured ports...
call :KILL_PORT "%BACKEND_PORT%" "backend"
if not defined SKIP_FRONTEND call :KILL_PORT "%FRONTEND_PORT%" "frontend"

echo.
echo [6/6] Starting services...
echo.
echo ============================================================
echo  Backend API:     http://%BACKEND_HOST%:%BACKEND_PORT%
echo  Swagger docs:    http://%BACKEND_HOST%:%BACKEND_PORT%/docs
echo  Test panel:      http://%BACKEND_HOST%:%BACKEND_PORT%/panel/
if not defined SKIP_FRONTEND echo  Frontend Vite:   http://%FRONTEND_HOST%:%FRONTEND_PORT%
echo.
echo  Press Ctrl+C to stop the foreground service.
echo  You can also run stop.bat to stop both configured ports.
echo ============================================================
echo.

if not defined SKIP_FRONTEND (
    if not defined NO_BROWSER start "" /b powershell -NoProfile -WindowStyle Hidden -Command "Start-Sleep -Seconds 5; Start-Process 'http://%FRONTEND_HOST%:%FRONTEND_PORT%/pc/home'"
    echo [i] Starting backend uvicorn in the background...
    start "ChaoXingAgent backend" /b uv run uvicorn src.api.app:app --host %BACKEND_HOST% --port %BACKEND_PORT% --no-use-colors

    echo [i] Starting frontend Vite dev server in the foreground...
    echo.
    cd /d "%PROJECT_DIR%\frontend"
    call npx vite --host %FRONTEND_HOST% --port %FRONTEND_PORT% --clearScreen false
    cd /d "%PROJECT_DIR%"
) else (
    if not defined NO_BROWSER start "" /b powershell -NoProfile -WindowStyle Hidden -Command "Start-Sleep -Seconds 5; Start-Process 'http://%BACKEND_HOST%:%BACKEND_PORT%'"
    echo [i] Starting backend uvicorn in the foreground...
    echo.
    uv run uvicorn src.api.app:app --host %BACKEND_HOST% --port %BACKEND_PORT% --no-use-colors
)

echo.
echo [i] Services stopped.
pause
exit /b 0

:KILL_PORT
set "PORT=%~1"
set "LABEL=%~2"
set "FOUND_PROCESS=0"
for /f "tokens=5" %%p in ('netstat -ano 2^>nul ^| findstr /C:":%PORT%" ^| findstr /C:"LISTENING"') do (
    echo [!] Port %PORT% is in use by %%p. Stopping old %LABEL% process...
    taskkill /f /pid %%p >nul 2>&1
    set "FOUND_PROCESS=1"
)
if "%FOUND_PROCESS%"=="0" echo [i] Port %PORT% is free.
exit /b 0
