from .base import BaseRequest, BaseResponse, SchemaModel
from .common import (
    DocumentUnit,
    DocumentUnitType,
    FileType,
    InputAsset,
    LearningProgress,
    LearningSession,
    LessonInfo,
    LessonStatus,
    NextAction,
    PageBlock,
    PageRole,
    ParsedDocument,
    QAHistoryItem,
    QARecord,
    ReferenceItem,
    ScriptBlock,
    SectionBlock,
    SectionType,
    SessionStatus,
    SourceFile,
    StructuredLessonContent,
    UnderstandingLevel,
)
from .decision_schemas import DecisionInput, DecisionOutput
from .generate_schemas import (
    GenerateInput,
    GenerateOutput,
    LessonScript,
    PPTOutline,
    PresentationCard,
    PresentationOutline,
    PresentationSection,
    SlideOutline,
    VisualPlan,
)
from .parser_schemas import ParserInput, ParserOutput
from .QA_schemas import QAInput, QAOutput
from .student_schemas import (
    KnowledgePointMatch,
    RetrievedContextItem,
    StudentAgentRequest,
    StudentAgentResponse,
    StudentQuestionType,
)
from .student_turn_context import StudentTurnContext

# Resolve forward reference: StudentAgentRequest.turn_context -> StudentTurnContext
StudentAgentRequest.model_rebuild()

__all__ = [
    "BaseRequest",
    "BaseResponse",
    "SchemaModel",
    "FileType",
    "DocumentUnitType",
    "PageRole",
    "SectionType",
    "LessonStatus",
    "SessionStatus",
    "UnderstandingLevel",
    "NextAction",
    "InputAsset",
    "SourceFile",
    "DocumentUnit",
    "LessonInfo",
    "PageBlock",
    "SectionBlock",
    "ParsedDocument",
    "StructuredLessonContent",
    "ScriptBlock",
    "ReferenceItem",
    "QAHistoryItem",
    "QARecord",
    "LearningSession",
    "LearningProgress",
    "ParserInput",
    "ParserOutput",
    "GenerateInput",
    "GenerateOutput",
    "VisualPlan",
    "PresentationCard",
    "PresentationSection",
    "PresentationOutline",
    "LessonScript",
    "SlideOutline",
    "PPTOutline",
    "QAInput",
    "QAOutput",
    "DecisionInput",
    "DecisionOutput",
    "StudentQuestionType",
    "KnowledgePointMatch",
    "RetrievedContextItem",
    "StudentAgentRequest",
    "StudentAgentResponse",
    "StudentTurnContext",
]
